apiVersion: v1
kind: PersistentVolume
metadata:
  name: semestre-volumen
  labels:
    semestre: ready
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 168.232.79.90
    path: "/home/sergio/umgDB2-master"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semestre-volumen
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      semestre: ready