apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  externalIPs:
  - 168.232.79.94
  selector:
    run: wordpress
  ports:
    - port: 3306