apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: mysql
spec:
  type: LoadBalancer
  externalIPs:
  - 168.232.79.94
  selector:
    run: mysql
  ports:
    - port: 3306