apiVersion: v1
kind: Service
metadata:
  name: mysql-router-service
  labels:
    app: mysql-router
spec:
  selector:
    app: mysql-router
  ports:
  - protocol: TCP
    port: 3306
  type: LoadBalancer
  loadBalancerIP: 168.232.79.94